sonar.projectKey=turiok.sonar-shellcheck
sonar.projectName=sonar-shellcheck
sonar.organization=turiok

sonar.sources=src/main/java
sonar.tests=src/test
sonar.java.binaries=target
sonar.coverage.jacoco.xmlReportPaths=target/jacoco.exec

